<%@ Page Title="Calendar Events" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CalendarEvents.aspx.cs" Inherits="WebApplication.CalendarEvents" Async="true" EnableEventValidation="false"%>
<asp:Content ID="Content1" runat="server" contentplaceholderid="MainContent">
    <br />
    <asp:TextBox ID="txtCalendarName" runat="server" OnTextChanged="txtCalendarName_TextChanged" Width="300px"></asp:TextBox>
    <br />
    <asp:Button ID="btnUpdateCalendarName" runat="server" OnClick="btnUpdateCalendarName_Click" Text="Change Calendar Name" Width="300px" />
    <br />
    <br />
    <asp:UpdatePanel runat="server">
        <ContentTemplate>
    <asp:Label ID="lblDate" runat="server" Text="Date: "></asp:Label>
    <br />
    <asp:Button ID="btnPreviousDay" runat="server" OnClick="btnPreviousDay_Click" Text="Previous" Width="100px" CausesValidation="False" />
    <asp:Button ID="btnNextDay" runat="server" OnClick="btnNextDay_Click" Text="Next" Width="100px" CausesValidation="False" />
    <br />
    <br />
    <asp:Label ID="Label1" runat="server" Text="Events"></asp:Label>
    <asp:GridView ID="gvEvents" runat="server" ShowHeaderWhenEmpty="True" AllowSorting="True" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="gvEvents_SelectedIndexChanged" OnRowCommand="gvEvents_RowCommand" AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="White" />
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:GridView>
            <asp:Button ID="btnNewEvent" runat="server" OnClick="btnNewEvent_Click" Text="Add New Entry" />
            <br />
        </ContentTemplate>
    </asp:UpdatePanel>
    <br />
</asp:Content>

